import { Record } from "./Record";

export const RECORDS : Record [] = [
    {
        id:1,
        firstName: "John",
        lastName: "Doe",
        address: "123 Elm Street",
        mobile: "555-1234",
        email: "john.doe@example.com",
        department: "Sales",
        designation: "Sales",
        updated: "2024-05-08 1:45 PM",
    },
    {
        id:2,
        firstName: "Jane",
        lastName: "Smith",
        address: "456 Oak Avenue",
        mobile: "555-5678",
        email: "jane.smith@example.com",
        department: "Marketing",
        designation: "Director",
        updated: "2024-03-08 2:10 PM",
    },
    {
        id:3,
        firstName: "Alice",
        lastName: "Johnson",
        address: "789 Pine Road",
        mobile: "555-8765",
        email: "alice.johnson@example.com",
        department: "HR",
        designation: "Coordinator",
        updated: "2024-03-08 2:30 PM",
    },
    {
        id: 4,
        firstName: "Bob",
        lastName: "Brown",
        address: "321 Maple Lane",
        mobile: "555-2345",
        email: "bob.brown@example.com",
        department: "IT",
        designation: "Technician",
        updated: "2024-03-08 3:00 PM"
    },
    {
        id: 5,
        firstName: "Charlie",
        lastName: "Davis",
        address: "654 Birch Boulevard",
        mobile: "555-3456",
        email: "charlie.davis@example.com",
        department: "Finance",
        designation: "Analyst",
        updated: "2024-03-08 3:15 PM"
    },
    {
        id: 6,
        firstName: "Eve",
        lastName: "Miller",
        address: "987 Cedar Street",
        mobile: "555-4567",
        email: "eve.miller@example.com",
        department: "Operations",
        designation: "Supervisor",
        updated: "2024-03-08 3:30 PM"
    },
    {
        id: 7,
        firstName: "Frank",
        lastName: "Wilson",
        address: "321 Spruce Way",
        mobile: "555-5678",
        email: "frank.wilson@example.com",
        department: "Legal",
        designation: "Consultant",
        updated: "2024-03-08 3:45 PM"
    },
    {
        id: 8,
        firstName: "Grace",
        lastName: "Lee",
        address: "654 Palm Drive",
        mobile: "555-6789",
        email: "grace.lee@example.com",
        department: "Engineering",
        designation: "Developer",
        updated: "2024-03-08 4:00 PM"
    },
    {
        id: 9,
        firstName: "Henry",
        lastName: "Taylor",
        address: "987 Fir Street",
        mobile: "555-7890",
        email: "henry.taylor@example.com",
        department: "R&D",
        designation: "Scientist",
        updated: "2024-03-08 4:15 PM"
    },
    {
        id: 10,
        firstName: "Isabel",
        lastName: "Anderson",
        address: "123 Aspen Court",
        mobile: "555-8901",
        email: "isabel.anderson@example.com",
        department: "Customer Support",
        designation: "Agent",
        updated: "2024-03-08 4:30 PM"
    },
    {
        id: 11,
        firstName: "Jack",
        lastName: "Thomas",
        address: "456 Cypress Avenue",
        mobile: "555-9012",
        email: "jack.thomas@example.com",
        department: "Quality Assurance",
        designation: "Inspector",
        updated: "2024-03-08 4:45 PM"
    },
    {
        id: 12,
        firstName: "Karen",
        lastName: "Jackson",
        address: "789 Redwood Road",
        mobile: "555-0123",
        email: "karen.jackson@example.com",
        department: "Logistics",
        designation: "Coordinator",
        updated: "2024-03-08 5:00 PM"
    },{
        id: 13,
        firstName: "Liam",
        lastName: "Martinez",
        address: "123 Willow Way",
        mobile: "555-1234",
        email: "liam.martinez@example.com",
        department: "Sales",
        designation: "Manager",
        updated: "2024-05-08 6:00 PM",
    },
    {
        id: 14,
        firstName: "Olivia",
        lastName: "Garcia",
        address: "456 Maple Road",
        mobile: "555-2345",
        email: "olivia.garcia@example.com",
        department: "HR",
        designation: "Manager",
        updated: "2024-06-08 10:15 AM",
    },
    {
        id: 15,
        firstName: "Sophia",
        lastName: "Martinez",
        address: "789 Birch Avenue",
        mobile: "555-3456",
        email: "sophia.martinez@example.com",
        department: "Finance",
        designation: "Senior Analyst",
        updated: "2024-07-10 11:00 AM",
    },
    {
        id: 16,
        firstName: "Lucas",
        lastName: "Hernandez",
        address: "321 Pine Lane",
        mobile: "555-4567",
        email: "lucas.hernandez@example.com",
        department: "Marketing",
        designation: "Executive",
        updated: "2024-08-05 2:45 PM",
    },
    {
        id: 17,
        firstName: "Mia",
        lastName: "Lopez",
        address: "654 Elm Avenue",
        mobile: "555-5678",
        email: "mia.lopez@example.com",
        department: "Operations",
        designation: "Manager",
        updated: "2024-08-15 4:30 PM",
    },
    {
        id: 18,
        firstName: "Noah",
        lastName: "Wilson",
        address: "987 Oak Court",
        mobile: "555-6789",
        email: "noah.wilson@example.com",
        department: "Engineering",
        designation: "Architect",
        updated: "2024-09-01 10:00 AM",
    },
    {
        id: 19,
        firstName: "Ava",
        lastName: "Roberts",
        address: "123 Cedar Road",
        mobile: "555-7890",
        email: "ava.roberts@example.com",
        department: "IT",
        designation: "Lead Developer",
        updated: "2024-09-15 12:15 PM",
    },
    {
        id: 20,
        firstName: "Ethan",
        lastName: "Johnson",
        address: "456 Redwood Lane",
        mobile: "555-8901",
        email: "ethan.johnson@example.com",
        department: "Customer Support",
        designation: "Team Lead",
        updated: "2024-10-01 1:30 PM",
    },
    {
        id: 21,
        firstName: "Isabella",
        lastName: "Taylor",
        address: "789 Pine Street",
        mobile: "555-9012",
        email: "isabella.taylor@example.com",
        department: "Quality Assurance",
        designation: "Manager",
        updated: "2024-10-10 3:00 PM",
    },
    {
        id: 22,
        firstName: "Mason",
        lastName: "Lee",
        address: "321 Cedar Court",
        mobile: "555-0123",
        email: "mason.lee@example.com",
        department: "Logistics",
        designation: "Supervisor",
        updated: "2024-11-12 9:45 AM",
    }
]